// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/sphinx-service/pkg/db/ent/keystore"
	"github.com/NpoolPlatform/sphinx-service/pkg/db/ent/predicate"
)

// KeyStoreDelete is the builder for deleting a KeyStore entity.
type KeyStoreDelete struct {
	config
	hooks    []Hook
	mutation *KeyStoreMutation
}

// Where appends a list predicates to the KeyStoreDelete builder.
func (ksd *KeyStoreDelete) Where(ps ...predicate.KeyStore) *KeyStoreDelete {
	ksd.mutation.Where(ps...)
	return ksd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ksd *KeyStoreDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ksd.hooks) == 0 {
		affected, err = ksd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*KeyStoreMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ksd.mutation = mutation
			affected, err = ksd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ksd.hooks) - 1; i >= 0; i-- {
			if ksd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ksd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ksd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ksd *KeyStoreDelete) ExecX(ctx context.Context) int {
	n, err := ksd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ksd *KeyStoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: keystore.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: keystore.FieldID,
			},
		},
	}
	if ps := ksd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ksd.driver, _spec)
}

// KeyStoreDeleteOne is the builder for deleting a single KeyStore entity.
type KeyStoreDeleteOne struct {
	ksd *KeyStoreDelete
}

// Exec executes the deletion query.
func (ksdo *KeyStoreDeleteOne) Exec(ctx context.Context) error {
	n, err := ksdo.ksd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{keystore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ksdo *KeyStoreDeleteOne) ExecX(ctx context.Context) {
	ksdo.ksd.ExecX(ctx)
}
