// Code generated by entc, DO NOT EDIT.

package coininfo

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the coininfo type in the database.
	Label = "coin_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCoinTypeID holds the string denoting the coin_type_id field in the database.
	FieldCoinTypeID = "coin_type_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUnit holds the string denoting the unit field in the database.
	FieldUnit = "unit"
	// FieldIsPresale holds the string denoting the is_presale field in the database.
	FieldIsPresale = "is_presale"
	// EdgeKeys holds the string denoting the keys edge name in mutations.
	EdgeKeys = "keys"
	// EdgeTransactions holds the string denoting the transactions edge name in mutations.
	EdgeTransactions = "transactions"
	// EdgeReviews holds the string denoting the reviews edge name in mutations.
	EdgeReviews = "reviews"
	// EdgeWalletNodes holds the string denoting the wallet_nodes edge name in mutations.
	EdgeWalletNodes = "wallet_nodes"
	// Table holds the table name of the coininfo in the database.
	Table = "coin_infos"
	// KeysTable is the table that holds the keys relation/edge.
	KeysTable = "key_stores"
	// KeysInverseTable is the table name for the KeyStore entity.
	// It exists in this package in order to avoid circular dependency with the "keystore" package.
	KeysInverseTable = "key_stores"
	// KeysColumn is the table column denoting the keys relation/edge.
	KeysColumn = "coin_info_keys"
	// TransactionsTable is the table that holds the transactions relation/edge.
	TransactionsTable = "transactions"
	// TransactionsInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionsInverseTable = "transactions"
	// TransactionsColumn is the table column denoting the transactions relation/edge.
	TransactionsColumn = "coin_info_transactions"
	// ReviewsTable is the table that holds the reviews relation/edge.
	ReviewsTable = "reviews"
	// ReviewsInverseTable is the table name for the Review entity.
	// It exists in this package in order to avoid circular dependency with the "review" package.
	ReviewsInverseTable = "reviews"
	// ReviewsColumn is the table column denoting the reviews relation/edge.
	ReviewsColumn = "coin_info_reviews"
	// WalletNodesTable is the table that holds the wallet_nodes relation/edge.
	WalletNodesTable = "wallet_nodes"
	// WalletNodesInverseTable is the table name for the WalletNode entity.
	// It exists in this package in order to avoid circular dependency with the "walletnode" package.
	WalletNodesInverseTable = "wallet_nodes"
	// WalletNodesColumn is the table column denoting the wallet_nodes relation/edge.
	WalletNodesColumn = "coin_info_wallet_nodes"
)

// Columns holds all SQL columns for coininfo fields.
var Columns = []string{
	FieldID,
	FieldCoinTypeID,
	FieldName,
	FieldUnit,
	FieldIsPresale,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// UnitValidator is a validator for the "unit" field. It is called by the builders before save.
	UnitValidator func(string) error
	// DefaultIsPresale holds the default value on creation for the "is_presale" field.
	DefaultIsPresale bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
