apiVersion: apps/v1
kind: Deployment
metadata:
  name: sphinx-service
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sphinx-service
  template:
    metadata:
      labels:
        app: sphinx-service
    spec:
      containers:
      - name: sphinx-service
        image: entropypool/sphinx-service:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: sphinx-service
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 50160
    targetPort: 50160
  - name: grpc
    port: 50161
    targetPort: 50161
  - name: prometheus
    port: 50163
    targetPort: 50163
  selector:
    app: sphinx-service